### PR TITLE
Added gzip support

### PR DESCRIPTION
**Pull request by BrandonDR**
- Automatically apply gzip compression if the destination ends with .tar.gz for the `create` command
- Updated readme and display_usage with examples

### CODE REVIEW

**Comment by junedkhatri31** [comment]
Thanks for the pull request. Can you please add support for `restore` as well?

**Comment by BrandonDR** [comment]
@junedkhatri31 Yeah no problem, `restore` works already.
`tar -xf something.tar.gz` will work with gz tar files without any extra options

https://linuxize.com/post/how-to-extract-unzip-tar-gz-file/#extracting-targz-file

**Comment by junedkhatri31** [comment]
That's nice. Thanks for pointing out.

Just gone over to the `tar` documentation over here - https://man7.org/linux/man-pages/man1/tar.1.html

Seems like `--auto-compress` or `a` option can automatically detect the compression as well. So instead we write compression logic manually, we could use this flag and have support for all compression algorithms. What are your thoughts?

**Comment by BrandonDR** [comment]
Yeah I agree, that seems like the way to go.
I have updated the code and re-tested

By the way, here is a size comparison for gz. Reduces disk space by 3x in my case.
Screenshot from 2023-10-10 11-05-53

**Comment by junedkhatri31** [comment]
That's nice

**Pull request merged**
